services:
  db_adil:
    image: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web_adil:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./test_adil:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_adil
