# Generated by Django 4.2.11 on 2024-04-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basededonnees",
            name="nom",
            field=models.CharField(
                choices=[
                    ("Scopus", "Scopus"),
                    ("PubMed", "PubMed"),
                    ("Dimensions", "Dimensions"),
                    ("Web of Science", "Web of Science"),
                ],
                max_length=100,
            ),
        ),
    ]
