# Generated by Django 4.2.11 on 2024-05-01 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_rename_adresse_email_utilisateur_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
